### PR TITLE
Go Opts CLI - goopts

### PR DESCRIPTION
**Pull request by millergarym**
Initial working version of goopts. Pronounced  /go opts/

```
  Usage: goopts init [options] <owner> <name>

  Options:
  --src-control-host, -s  default github.com
  --package, -p
  --command, -c
  --directory, -d         output directory (default .)
  --help, -h              display help
```

### CODE REVIEW

**Comment by millergarym** [comment]
A nice demo

```
goopts init -d yyyy yyyyy zzzzz
cd yyyy
goreleaser release --skip-publish --skip-validate
```

**Comment by jpillora** [comment]
Ah cool, thanks gary. Because the tool is stand-alone, like `opts-examples`, maybe it could be a separate repo like "go-opts" or "opts-cli"? Hoping to keep `opts` as barebones as possible

**Comment by millergarym** [comment]
Up to you

**Comment by jpillora** [comment]
Alrighty, pushed to https://github.com/jpillora/opts-cli

The command per package along with the `Register` function is a good pattern, and was thinking of adding a `Call` method

```go
	//Call the given function with this instance of Opts.
	//This allows a registration pattern where the callee
	//can add multiple commands, adjust the documentation,
	//and more.
	Call(func(Opts)) Opts
```

which will allow for:

```
opts.New(&root).Call(foo.Register).Parse()
```

Thoughts?

**Comment by jpillora** [comment]
Maybe not worth the added surface... I guess its not too ugly:
```go
o := opts.New(&root)
foo.Register(o)
o.Parse()
```

**Comment by millergarym** [comment]
I don't know, sounds like a really nice idea to me.

The opt-cli `main.go` is actually quite ugly

``` go
type root struct {
	parsedOpts opts.ParsedOpts
}

func main() {
	r := root{}
	ro := opts.New(&r).
		EmbedGlobalFlagSet().
		Complete().
		Version(Version)

	initopts.Register(ro)

	r.parsedOpts = ro.Parse()
	err := r.parsedOpts.Run()
	if err != nil {
		fmt.Fprintf(os.Stderr, "run error %v\n", err)
		os.Exit(2)
	}
}
```

This could be

``` go
type root struct {
	ParsedOpts opts.ParsedOpts `opts:"mode=parsedOpts"`
}

func main() {
	opts.New(&root{}).
		EmbedGlobalFlagSet().
		Complete().
		Version(Version).
		Call(initopts.Register).
		Parse().
		RunFatal()
}
```

Four assignments verse Zero.

**Pull request closed without merging**
